### GET確認
GET http://localhost:3000/users

###

### POST追加
POST http://localhost:3000/users
Content-Type: application/json

{ "name": "saburo" }

### GET確認
GET http://localhost:3000/users

### PATCH更新
PATCH http://localhost:3000/users/1
Content-Type: application/json

{ "name": "jiro" }

### DELETE削除
DELETE http://localhost:3000/users/1

### GET確認
GET http://localhost:3000/users

##

### ユーザー登録
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "saburo",
  "email": "saburo@example.com",
  "password": "password123"
}

### ログイン
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "saburo@example.com",
  "password": "password123"
}


##

### 1. トークンなしでGET（401になるはず）
GET http://localhost:3000/users

### 2. ログインしてトークン取得
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "saburo@example.com",
  "password": "password123"
}

### 3. トークンありでGET（200になるはず）
GET http://localhost:3000/users
Authorization: Bearer ここにトークンを貼る


### 存在しないidにPATCH（404になるはず）
PATCH http://localhost:3000/users/999
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3MzAxNzE1NCwiZXhwIjoxNzczMTAzNTU0fQ.HnHnqepzoW4t1t870rQxKaxi0TMbXfcHLw1drWTRGI4
Content-Type: application/json

{ "name": "test" }

### 同じemailで登録（409になるはず）
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "saburo2",
  "email": "saburo@example.com",
  "password": "password123"
}

### ログイン（accessToken + refreshToken が返るか確認）
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "saburo@example.com",
  "password": "password123"
}

### トークンリフレッシュ
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc3MzI4MDU2NCwiZXhwIjoxNzczODg1MzY0fQ.r5eeUqrTPUQzMLx2iSZIvypsab_HrSeHwFOoz6AQH30"
}

### ログアウト
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc3MzI4MDU2NCwiZXhwIjoxNzczMjgxNDY0fQ.VsmMFNA_P_4ED2SCe8RD-b716kTM6-G3m24rR4itm2I


### ユーザー詳細取得
GET http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc3MzMwMDQ3OCwiZXhwIjoxNzczMzAxMzc4fQ.BmnpoRPYt0PRvi0hhmYt4SkKYhdtKgNhBM1_JjM8BNY